### ISSUE TITLE
Add support for --argumentfile

### ISSUE THREAD

**Issue by IlfirinPL** [robotframework/MavenPlugin#27]
It would be usefull to be able run test from RIDE using maven without support of --argumentfile its not possible

**Comment by jussimalinen** [comment]
There should be support for that: http://robotframework.org/MavenPlugin/run-mojo.html#argumentFile

Arguments are given with -D prefix and they are case sensitive. 
 -DargumentFile=myfile.txt

**Comment by IlfirinPL** [comment]
Ok, thank you I forgot about casesensitve
