### ISSUE TITLE
libdoc does not pass java dependencies to javadoc properly

### ISSUE THREAD

**Issue by diakula** [robotframework/MavenPlugin#29]
I use the maven plugin, and when I attempt to generate a `libdoc` for a Java keyword library I get "error: cannot find symbol " messages for all classes that the library class imports from non-jdk modules. 

I have added dependencies on the jars to the plugin section, but same result.

When I do the same for a class that does not use anything but JDK classes, I get everything OK.

I could only get it to work when supplying `-Xbootclasspath/a:dependency.jar` to the MAVEN_OPTS, which indicates an specific isolated bug in the maven plugin, not passing dependencies to the `libdoc`.

I also tried on the command line with `java -jar robot.jar libdoc file.java file.html` and I could only get it to work when supplying `-Xbootclasspath/a:tools.jar:dependency.jar`, the -P did not work for Java dependencies. For the `tools.jar`, I understand. Hmmm, this perhaps point to a missing feature of `libdoc` Jython integration not possible to pass Java dependencies

**Comment by diakula** [comment]
The framework team has acknowledged this as a non-urgent bug in `libdoc`, so we can expect some time for them to fix. Then we would need to test with the Maven plugin and then make a release.

**Comment by jussimalinen** [comment]
Right... I hope we can get https://github.com/robotframework/robotframework/issues/1933 to Robot 2.9

**Comment by Hi-Fi** [comment]
At least I haven't seen this kind of error with my Java libraries, so this is probably fixed. Closing issue.
