### ISSUE TITLE
variableFiles in java isn't being read successfully with Maven

### ISSUE THREAD

**Issue by thejordaniandude** [robotframework/MavenPlugin#33]
Hello,
I'm using Robot Framework Maven Plugin with Eclipse to mavenize RF test cases. When I specify a Variables file either in the test case settings or in the POM file, in both cases running the maven project fails showing the following error:

[ ERROR ] Processing variable file "\User\myuser\.....\Variables.java" failed: AttributeError: instance attr: class

I tried passing the variables using <variables> option in the pom file and it worked fine.
I tried passing the Variables file path in the test case and running the pybot command from the terminal and it worked fine too. 

The problem arrises only when running the project as maven. 
Please advice.

**Comment by diakula** [comment]
I use
```
<variableFiles>
	<variableFile>${basedir}/input_variables.py</variableFile>
</variableFiles>
```
and on the command line the following parameter
```
--variablefile input_variables.py
```
and it works. Mind that the file has Python syntax:
```
varname = "value string"

Does this work for you?

**Comment by thejordaniandude** [comment]
Thanks for your reply diakula, I'm using Java actually!

**Comment by diakula** [comment]
I am using Java as well. Still, variablefile has to come in phyton format. Jython will compile dynamically, so you can continue using from Java.

**Comment by thejordaniandude** [comment]
Thanks diakula I just tried it now and it worked! I was hoping to make it work also for a java variable file but this would do the job :) thanks again.

**Comment by diakula** [comment]
Great! A few minor notes - to my opinion, the external variables should serve the sole purpose to parametrise or wire up your tests with external modules/context. As such, the variable file contains the simplest form of variable declarations, name/value pairs. Robotframework seems to support Python files, but Java *.property files have same format ('name=value' on each line). You work with property files via the Properties class. Java has no direct support to compile properties or variable - Python does.
