### ISSUE TITLE
Includes and Excludes in pom.xml does not seem to work

### ISSUE THREAD

**Issue by michelmeeuwissen** [robotframework/MavenPlugin#35]
The includes or excludes tag doesn't seem to work when setup in de pom.xml:

```
<plugin>
	<groupId>org.robotframework</groupId>
	<artifactId>robotframework-maven-plugin</artifactId>
	<version>1.4.4</version>
	<executions>
		<execution>
			<goals>
				<goal>acceptance-test</goal>
			</goals>
			<configuration>
				<includes>Foo</includes>
				<reportTitle>Acceptance tests</reportTitle>
				<variables>
				</variables>
			</configuration>

		</execution>
	</executions>
</plugin>
```

Or:

```
<plugin>
	<groupId>org.robotframework</groupId>
	<artifactId>robotframework-maven-plugin</artifactId>
	<version>1.4.4</version>
	<executions>
		<execution>
			<goals>
				<goal>acceptance-test</goal>
			</goals>
			<configuration>
				<includes>
					<include>Foo</include>
				</includes>
				<reportTitle>Acceptance tests</reportTitle>
				<variables>
				</variables>
			</configuration>
		</execution>
	</executions>
</plugin>
```
On the command line it does work:
    
`mvn robotframework:run -Dincludes=Foo`

**Comment by jussimalinen** [comment]
I really cant replicate this. When I try this, the includes work just fine when used as in your second example.

Can you perhaps create a very simple example project that recreates the problem?

**Comment by michelmeeuwissen** [comment]
I just found the problem.

If I use the following it works:

````
<plugin>
	<groupId>org.robotframework</groupId>
	<artifactId>robotframework-maven-plugin</artifactId>
	<version>1.4.4</version>
	<executions>
		<execution>
			<goals>
				<goal>acceptance-test</goal>
			</goals>            
		</execution>
	</executions>
	<configuration>
		<includes>
			<include>Foo</include>
		</includes>
		<reportTitle>Acceptance tests</reportTitle>
		<variables>
		</variables>
	</configuration>
</plugin>
````

Please check the location of the configuration tag. My IDE (Intellij) was complaining about the location so I moved it outside the execution tag which solved the IDE validation error. 

See warning IDE:
![image](https://cloud.githubusercontent.com/assets/7009844/9223677/886807b6-40fc-11e5-8d19-cff71dfae0fa.png)


Solution: Use configuration for includes and excludes outside the executions tag

Thanks

**Comment by jussimalinen** [comment]
This is rather weird. I have an example project where I have the configuration element within the execution tag, just as your example, and it works just fine.

Maybe you were not running the acceptance-test goal, to which execution the configuration was added? Or maybe this is a maven version thing. Which maven version are you using?

**Comment by michelmeeuwissen** [comment]
I both tried `robotframework:acceptance-test` and `robotframework:run` without success.

I used maven 3.3

**Comment by jussimalinen** [comment]
hmm.. very odd. I just have no idea what is happening there. Many of our own projects are using the execution specific configurations, so it really should work. I have no idea which way to go to replicate your issue.

I guess your workaround is good enough for you?

**Comment by michelmeeuwissen** [comment]
Yes the workaround is fine. I'm going to try to create a sample project to see if I can reproduce the problem in a skeleton project.

I'll keep you posted.

Thanks

**Comment by michelmeeuwissen** [comment]
I created a sample project:

https://github.com/michelmeeuwissen/RobotFramework-maven-selenium

See the output in folder doc for more information.

in short:
The include tag in configuration in the execution element does not work when executing the command `mvn robotframework:run` 

Running `mvn clean install` works

**Comment by jussimalinen** [comment]
Thanks for the example. Running it with different configurations I get this result:

mvn integration-test
    include works

mvn robotframework:acceptance-test
    include does not work

It seems that if I execute the specific goals with robotframework: -prefix, then the configuration within executions ignored.

**Comment by jussimalinen** [comment]
According to https://maven.apache.org/guides/mini/guide-configuring-plugins.html#Using_the_executions_Tag that behaviour is expected.

Quote from that page:

*Note: Configurations inside the <executions> tag differ from those that are outside <executions> in that they cannot be used from a direct command line invocation. Instead they are only applied when the lifecycle phase they are bound to are invoked. Alternatively, if you move a configuration section outside of the executions section, it will apply globally to all invocations of the plugin.*

**Comment by jussimalinen** [comment]
Well, I learned something new about Maven today. Thanks for going through the trouble to make an example project. I'll close this issue as the plugin seems to work as expected.
