### ISSUE TITLE
"BuiltIn.Import Resource" failing with "Resource does not exist" on running tests using robotframework maven plugin 1.4.5

### ISSUE THREAD

**Issue by ankit87** [robotframework/MavenPlugin#39]
I am trying to run a simple robot test which tries to import a resource file using "Import Resource" keyword using maven plugin 1.4.5 version (with robotframework 2.9.2 dependency) but it is failing with error message "Resource file <file name> does not exist".

I am using the Import Resource keyword in the following format:
Import Resource             ${CURDIR}${/}variables.tsv

Strange thing is that if i try to run the same test using jybot or pybot, the same test runs successfully. Please see robot report (import_resource_report_using_jybot) when tests are run using jybot. 

NOTE:
1. I have tried using maven 2.2.1 and 3.0.5 and it fails with both the versions
2. I am trying using maven plugin version 1.4.5 and robot 2.9.2/2.9.1
>			<plugin>
				<groupId>org.robotframework</groupId>
				<artifactId>robotframework-maven-plugin</artifactId>
				<version>1.4.5</version>
				<dependencies>
					<dependency>
						<groupId>org.robotframework</groupId>
						<artifactId>robotframework</artifactId>
						<version>2.9.2</version>
					</dependency>
				</dependencies>
>			</plugin>			

3. If I use robot framework 2.8.7 with same 1.4.5 maven plugin, the same test pass, that means it is a regression with 2.9.1/2.9.2 robot framework version.
4. If you observe the attached sample test file, I am also using OperatingSystem.Get File keyword which works fine without any issues.

Could you please take a look and suggest if we need to configure any additional properties to be able to run tests successfully using maven plugin. 
Due to this issue, a lot of our existing tests using Import Resource keyword (which were working with previous version) are failing and therefore couldn't use this version

Below is a snapshot of test implementation:
![importresourcetest](https://cloud.githubusercontent.com/assets/15625439/10902643/eb66d390-8226-11e5-871f-b1f43ecac25b.JPG)

Below is a snapshot of robot logs when run using jybot and robot framework 2.9.2 where Import Resource keyword pass.
![import_resource_report_using_jybot](https://cloud.githubusercontent.com/assets/15625439/10903622/b9fe41a2-8231-11e5-99de-3381e326a2de.JPG)

Below is a snapshot of robot logs when run using robot 2.9.2 and maven plugin 1.4.5 where Import Resource keyword fail.
![import_resource_report_using_maven](https://cloud.githubusercontent.com/assets/15625439/10903623/b9fe74d8-8231-11e5-8a89-28a47eed892a.JPG)

**Comment by ankit87** [comment]
I tried opening the issue initially in robtoframework (see https://github.com/robotframework/robotframework/issues/2192) but it is suggested the issue should be opened for maven plugin instead of  robotframework as it works fine when running the same tests using pybot/jybot directly.

I have created a simple example maven project but unfortunately i can't upload zip files on github. Do you know if there is any way to do so?
Btw, I am uploading sample robot test txt files here for reference and also pom.xml (as pom.txt) i am using.
[ImportResourceTest.txt](https://github.com/robotframework/robotframework/files/42842/ImportResourceTest.txt)
[variables.txt](https://github.com/robotframework/robotframework/files/42843/variables.txt)
[pom.txt](https://github.com/robotframework/robotframework/files/42844/pom.txt)

**Comment by jussimalinen** [comment]
This turned out to be Robot Framework core issue (that will only show up on standalone jar-distribution, and therefore also with MavenPlugin.). See robotframework/robotframework#2192 for a workaround while waiting for 3.0 release.
