### ISSUE TITLE
Extending Support for plugin execution using robot along with jybot for robotframework 3.0 and higher

### ISSUE THREAD

**Issue by krishnagkashyap** [robotframework/MavenPlugin#43]
I have the following plugin configured, now, when i install few packages( requests modules using pip on python ) and run the below plugin, the same fails to identify the modules installed as the plugin only runs using jybot and not using robot.

When we see Executing Testcases section only "robot " would be available going forward, and all other versions of execution invocation would be eventually deprecated. Hence, requesting you to provide support for the same in the next version of the plugin.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#executing-test-cases

        <plugins>
            <plugin>
                <groupId>org.robotframework</groupId>
                <artifactId>robotframework-maven-plugin</artifactId>
                <version>1.4.7</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>

**Comment by Hi-Fi** [comment]
No comments, and RF 3+ supported, so closing this.
