### ISSUE TITLE
Plugin does not work with Java9+

### ISSUE THREAD

**Issue by aquator** [robotframework/MavenPlugin#45]
From jigsaw activating profiles to load tools.jar or classes.jar is broken, to the plugin fails.

**Comment by aquator** [comment]
See https://github.com/robotframework/MavenPlugin/pull/44 with potential fix.

**Comment by Hi-Fi** [comment]
If I understood correctly, the fix for this is coming at the RF 3.1? So the fix in Maven plugin (updating RF version) comes after it's released.

Did I understood issues and PRs correctly?

**Comment by Hi-Fi** [comment]
Thank you for verification. I'll try to remember refer this issue when RF 3.1 gets released and I'll make new version of MavenPlugin.

**Comment by aquator** [comment]
Nah, the profile activation fix is still needed, this way it will try to get non-existent jars. If all goes well RobotFramework will be released today, so I can fiddle with it.

**Comment by Hi-Fi** [comment]
Fixed in 1.5.0. Big thanks for the fix.
