### ISSUE TITLE
Flattening keywords?

### ISSUE THREAD

**Issue by patrijuh** [robotframework/MavenPlugin#49]
Hi,

To reduce the amount of memory needed for creating html report, I would like to flatten keywords.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#flattening-keywords

Is this possible when using Robot Framework Maven plugin? Or should we just set logFile config to value NONE and use rebot to generate the html reports?

**Comment by Hi-Fi** [comment]
Is it enough to use new rebot goal to generate HTMLs? So running the tests first with log, report and xunit set to NONE, and then generate those with rebot goal (http://robotframework.org/MavenPlugin/rebot-mojo.html)?

Support for flattening is quite easy to implement, but the rebot approach is available now.
