### ISSUE TITLE
is there a way to rerun failed suites?

### ISSUE THREAD

**Issue by endrohat** [robotframework/MavenPlugin#61]

**Comment by Hi-Fi** [comment]
No, currently there's no option to input --rerunfailed -option through Maven goal.

**Comment by php-coder** [comment]
How the new option is different from [`runFailed`](https://robotframework.org/MavenPlugin/run-mojo.html#runFailed)?

**Comment by Hi-Fi** [comment]
Apparently I did exactly same thing again. So no difference, probably need to remove the rerunFailed.

Went too quickly through the things before release.
