### ISSUE TITLE
Out of memory when generating report with rebot goal

### ISSUE THREAD

**Issue by patrijuh** [robotframework/MavenPlugin#64]
We are using rebot goal to generate report from output.xml AFTER we have already ran the tests. It seems that running tests with logFile config as NONE and creating the report afterwards with rebot goal is not helping much as report generation with rebot goal still uses too much memory and fails.

...
[INFO] --- robotframework-maven-plugin:1.5.1:rebot (default) @ accceptance-testing ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  09:18 min
[INFO] Finished at: 2019-04-24T01:52:24Z
[INFO] ------------------------------------------------------------------------
[ERROR] GC overhead limit exceeded -> [Help 1]

We are having ~300 tests in our test build where this fails.

**Comment by Hi-Fi** [comment]
I think it's not about the amount of the tests, but lines in the output.xml.

There's not much that can be done with the code side, as code just calls RF with Jython, and issue is (probably) at the Jython itself. Only way to make this more robust would be to write completely own report parser for Java, which doesn't probably be reasonable.

Workaround is to have the log parsing with rebot using Python and RF directly, That's also much faster compared to Jython one.

**Comment by patrijuh** [comment]
Yes, workaround can be done. It's just makes things a bit more complicated because of the extra python and RF installation(s) to all of our agents where we run our robot cases. Would have been nice to have all the needed in one Maven pom.xml. I think this issue can be closed.
