### ISSUE TITLE
Add support for controlling console output

### ISSUE THREAD

**Issue by php-coder** [robotframework/MavenPlugin#67]
I see that version on Python supports `--console` options (see http://robotframework.org/robotframework/3.1.2/RobotFrameworkUserGuide.html#controlling-console-output) that can be used for controlling verbosity.

Could we have such support as well?

**Comment by php-coder** [comment]
@Hi-Fi WDYT?

**Comment by Hi-Fi** [comment]
I don't see any reason why not. Basically plugin just "pipes" parameters through, so it's just matter of defining the structure in plugin and testing that things works as should.

**Comment by php-coder** [comment]
Thanks! Looking forward to try it with the next release.
