### ISSUE TITLE
Publish 1.6.0 to Maven Central

### ISSUE THREAD

**Issue by php-coder** [robotframework/MavenPlugin#74]
Could we have 1.6.0 on Maven Central? At this moment it isn't there: https://mvnrepository.com/artifact/org.robotframework/robotframework-maven-plugin

Thanks!

**Comment by Hi-Fi** [comment]
Interesting, as job seemed to pass as should: https://github.com/robotframework/MavenPlugin/runs/374696569

Has to check that.

**Comment by Hi-Fi** [comment]
Mvnrepository has some issue, as official search shows it: https://search.maven.org/artifact/org.robotframework/robotframework-maven-plugin

**Comment by php-coder** [comment]
Hm, Travis also don't see this artifact: https://travis-ci.org/php-coder/mystamps/jobs/640093088

Ok, thanks, I'll re-trigger it later and I hope that it will be available.

**Comment by Hi-Fi** [comment]
Interesting. As release is visible at Central search, all I could do is make release with new  version. And still it would be unclear why that was not synced correctly as e.g. JavalibCore was.

**Comment by php-coder** [comment]
It seems like it was cache-related issue on Travis. I cleared the caches (https://docs.travis-ci.com/user/caching/#clearing-caches) and builds are green now.
