### ISSUE TITLE
Support for Python 3

### ISSUE THREAD

**Issue by raka2407** [robotframework/MavenPlugin#80]
Hi, 

I have custom made robot framework libraries build on Python 3. I now intend to utilize robotframework-maven-plugin and add my python based robotframework libraries as POM dependencies. I was able to achieve this configuration using jython-compile-maven-plugin. However I see a limitation to be able to run my custom python libraries on Python 2. 7. 

Below is the code snippet used in POM.xml

` <plugins>
  <plugin>
        <groupId>org.robotframework</groupId>
        <artifactId>robotframework-maven-plugin</artifactId>
        <version>1.7.2</version>
        <configuration>
			      <xunitFile>target/robotframework-reports/xunit.xml</xunitFile>
            <argumentFile>src/test/resources/config/runtime.args</argumentFile>
            
		</configuration>  
        <executions>
          <execution>
            <goals>
               <goal>acceptance-test</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
            <groupId>net.sf.mavenjython</groupId>
            <artifactId>jython-compile-maven-plugin</artifactId>
            <version>2.0</version>
            <executions>
                   <execution>
                          <phase>package</phase>
                          <goals>
                               <goal>jython</goal>
                          </goals>
                   </execution>
            </executions>
            <configuration>
                  <libraries>
                        <param>custom-python-library</param>
                  </libraries>
            </configuration>
      </plugin>
    </plugins>`

What I understand with the limitation is that robotframework-maven-plugin under the hood relies on Jython 2.7 which internally uses Python 2.7 whereas my custom python libraries are built on Python 3. 

Is there a possibility to configure the python environment that I intend to use for execution ?  

I would like to know the way forward and appreciate if any guidance can be provided on the way forward with this issue. Thanks!

**Comment by Hi-Fi** [comment]
As you noticed and stated already, Jython sadly support only Python 2(.7.2), and there's no clear plans at least if there's even going to be Jython supporting Python 3. That's something that's thought at the RF core's side, too (related e.g. to Python 2 support).

About current possibilties:
1) Maven exec plugin, and start Python3 library as remote library. Requires of course that all machines running has Python3 available
2) Package library as docker image (with remote server), and start it from Maven. Requires possibilty to run containers everywhere tests are running (made that kind of possibility to https://github.com/MarketSquare/robotframework-httprequestlibrary/blob/develop/pom.xml#L136-L215 with profile `localRun`
3) Deploy those needed Python libraries to some server to be used remotely.

**Comment by Tattoo** [comment]
I also have this issue. Option #1 would be probably easiest and most flexible. Options #2 & #3 one can build themselves while they know a lot of details.

**Comment by Hi-Fi** [comment]
> Is there a possibility to configure the python environment that I intend to use for execution ?

Not sure if getting this, but is is basically https://github.com/robotframework/MavenPlugin/issues/3? If it is that, then kind of option 1 is to use maven exec to run the tests with pure Python3. Log parsing can be done (if wanted) either with Maven-plugin or at Python side.

**Comment by raka2407** [comment]
> > Is there a possibility to configure the python environment that I intend to use for execution ?
> 
> Not sure if getting this, but is is basically existing issue #3? If it is that, then kind of option 1 is to use maven exec to run the tests with pure Python3. Log parsing can be done (if wanted) either with Maven-plugin or at Python side.

**Comment by raka2407** [comment]
> > Is there a possibility to configure the python environment that I intend to use for execution ?
> 
> Not sure if getting this, but is is basically existing issue #3? If it is that, then kind of option 1 is to use maven exec to run the tests with pure Python3. Log parsing can be done (if wanted) either with Maven-plugin or at Python side.

What I meant here is similar to existing issue #3. As we know that by default Python 2.7 is used by the plugin, I intend to override this default behavior with a provision to provide python interpreter.  I looked at <externalRunner> parameter but I was not able to relate it to configure python. 

I will try with option 1 suggested above. Thanks!

**Comment by Hi-Fi** [comment]
I have thought #3 a bit, but it's quite close to the thing you can already do with Maven Exec -plugin.

**Comment by raka2407** [comment]
This is how I got Option 1 (Maven exec plugin + python 3 library as Remote library) configured. Please suggest if there is a better way to do this. Thanks!

**POM.xml with maven exec plugin and executable as robot**

`<plugin>
            <groupId>org.codehaus.mojo</groupId>
            <artifactId>exec-maven-plugin</artifactId>
            <version>1.6.0</version>
            <executions>
                <execution>
                    <configuration>
                        <executable>robot</executable>
                        <workingDirectory>src/test/robotframework/acceptance/</workingDirectory>
                        <arguments>
                            <argument>tests.robot</argument>
                        </arguments>
                    </configuration>
                    <id>python_build</id>
                    <phase>generate-resources</phase>
                    <goals>
                        <goal>exec</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>`


**Configuring python 3 library as remote library and started on Python**

Followed the reference from this link https://github.com/robotframework/PythonRemoteServer/tree/master/example

I have 10+ custom python libraries and to be able to configure each of such library as remote library, I need to 

1. Add the following lines of code in the class file of the library.

    `import sys`
    `from robotremoteserver import RobotRemoteServer`

Also, towards the end of the file,  add the following code 
  
    `if __name__ == '__main__':`
    `RobotRemoteServer(Keywords(), *sys.argv[1:])`

2. I need to add an import statement in each of the test suites that use the remote library. 

    `*** Settings ***`
    `Library       Remote    http:/127.0.0.1:8270`

**Comment by Hi-Fi** [comment]
One thing you should note that now you expect that one static port is available. I recommend to use plugin that reserves free ports which can be used as argument in remote server start: https://github.com/MarketSquare/robotframework-httprequestlibrary/blob/develop/pom.xml#L144-L163.

Server itself can also tell it's active port, but it's harder to read it back to Maven execution than mentioned plugin. Also that remote library's host and port should be variables, so it's easy to change those if at some point e.g. libraries are deployed to common place.

**Comment by Hi-Fi** [comment]
Just released version 1.8.0 has possibility to run tests with Python runner. OFC Java based libraries are not working directly, but ways to get those working are presented better way at [Robocon](https://robocon.io/#robot-framework-after-jython), but briefly possibilities:
- Remote library
- Pyjnius
- Py4J
- JPype

First one's issue is that Listeners are not working with those. 

Demos in the presentation are published at the Robocon along with repository to play with examples self.

**Comment by Thrameos** [comment]
I would be happy to answer any questions about JPype to help determine if it is a suitable option or if one of the others is a better choice.  Though you would need to lay out the requirements.  Does Java need to be able to call Python code?  Do you need to restart the JVM?  How many Java classes need to be exposed under  Python?

**Comment by Hi-Fi** [comment]
I actually have examples working for each option (just with exec, so have to change back to MavenPlugin). I'll try to see if there's a way to put one over another, but at least I can show pros and cons in presentation.

Pyjnius and Py4J are in a way simpler options, as those handle JVM self.
