### ISSUE TITLE
Upload error when using latest plugin version

### ISSUE THREAD

**Issue by MarkaRagnos0815** [robotframework/MavenPlugin#83]
We have an issue your latest plugin version
when trying to upload data it fails using the robot framework built in requests library

we tried the following combinations
plugin 1.6.0 + robotframework request library 0.7.0 -> Upload succeeds
plugin 1.6.0 + robotframework request library 0.7.1 -> Upload succeeds
plugin 1.7.2 + robotframework request library 0.7.0 -> Upload fails 
plugin 1.7.2 + robotframework request library 0.7.1 -> Upload fails

Stack trace from python:

```
Error in robot report:
	Traceback (most recent call last):
  File "\robot-tests\target\robot-filtered\external-libs\RequestsLibrary\RequestsKeywords.py", line 677, in post_request
    response = self._common_request(
  File "\robot-tests\target\robot-filtered\external-libs\RequestsLibrary\RequestsKeywords.py", line 938, in _common_request
    resp = method_function(
  File "\robot-tests\target\robot-filtered\external-libs\requests\sessions.py", line 578, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "\robot-tests\target\robot-filtered\external-libs\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "\robot-tests\target\robot-filtered\external-libs\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "\robot-tests\target\robot-filtered\external-libs\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
```

What we did:
```
*** Settings ***
Library     RequestsLibrary
Test Template   Upload Something To Server

*** Test Cases ***                  Document
Process File                        test-file.tif

*** Keywords ***
Upload Something To Server
    [Arguments]     ${document}
    Create Session          Server  http://{server-ip}:{server-port}
    ${file}=        Get File For Streaming Upload   ${document}
    &{file_data}=   Create Dictionary   file=${file}
    ${document-id}=     Post Request  Server  /upload-endpoint files=${file_data}
```

it seems only to happen with latest plugin version independent of the requests library version

**Comment by Hi-Fi** [comment]
Is there some keywords or things missing that you can't use https://github.com/MarketSquare/robotframework-httprequestlibrary?

Related to issue change between 1.6.x to 1.7.x was just RF version (from 3.1.2 to 3.2), which introduced change to Jython version (2.7.0 to 2.7.2): https://github.com/robotframework/robotframework/commit/bdd3a223dda74bb4afe726b0f8f3198171ef2264#diff-2e746c9eacad6e2c2fdefdc6a665b5ce4607ea384ebf97a729044b79acc778d6

So Maven plugin basically can't do much, and options basically are:
1. Use Java version of requests library
2. Use requests library as remote library (need Python installation to run that, or Docker)
3. Run everything with pure Python 3.

**Comment by MarkaRagnos0815** [comment]
thanks for the information
