### ISSUE TITLE
robotframework maven plugin is not importing cython based python modules like lxml

### ISSUE THREAD

**Issue by simplyviks** [robotframework/MavenPlugin#84]
i am trying to use a keyword in test case from a python module that imports some library from lxml as shown below.
but the import fails, i have made sure its present in PYTHONPATH, by setting extraPathDirectory.

i have tried all options to get the module imported but still no luck, has it something to do with lxml being a cython package.?
from lxml import etree
from lxml.etree import _Element, _ElementTree as ET

traceback (most recent call last): File "/XX/test.py", line 3, in <module> from lxml import etree 

PYTHONPATH:

reference ticket.
https://github.com/kootstra/robotframework-allurereport/issues/9

**Comment by Hi-Fi** [comment]
This is known limitation with Jython, as it can't use modules based on C.

See e.g. https://stackoverflow.com/questions/53815005/jython-can-not-use-lxml-library
