### ISSUE TITLE
Support Cython based python modules with Jython

### ISSUE THREAD

**Issue by simplyviks** [robotframework/MavenPlugin#88]
Hi All,

I am aware of the limitation of jython supporting cython based dependency, is there any other way to achieve this?

basically I want to run some python modules with cython dependency using maven-robot-framework plugin.

Any help or lead is highly appreciated, Thanks in Advance!!

**Comment by Hi-Fi** [comment]
There's no way than Jython could run Python modules written in C. Only ways to have those is to use remote library to expose those libraries. Or move running fully to be made with Python RF, and offer Java libraries some other way.

Examples of latter at https://github.com/Hi-Fi/robotframework-after-jython.
